# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "DEV" ]
  pull_request:
    branches: [ "DEV" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    env:
      SOLUTION_FILE: "PowerPoint\\VSTO PPT AddIn Clean SlideMaster\\VSTO PPT AddIn Clean SlideMaster.slnx"
      PROJECT_DIR: "./PowerPoint/VSTO PPT AddIn Clean SlideMaster/VSTO PPT AddIn Clean SlideMaster"
      PROJECT_FILE: "PowerPoint\\VSTO PPT AddIn Clean SlideMaster\\VSTO PPT AddIn Clean SlideMaster\\VSTO PPT AddIn Clean SlideMaster.csproj"
      CONFIGURATION: Release

      OUT_DIR: "./PowerPoint/VSTO PPT AddIn Clean SlideMaster/VSTO PPT AddIn Clean SlideMaster/bin/Release"
      APP_MANIFEST: "./PowerPoint/VSTO PPT AddIn Clean SlideMaster/VSTO PPT AddIn Clean SlideMaster/bin/Release/VSTO PPT AddIn Clean SlideMaster.dll.manifest"
      DEPLOY_MANIFEST: "./PowerPoint/VSTO PPT AddIn Clean SlideMaster/VSTO PPT AddIn Clean SlideMaster/bin/Release/VSTO PPT AddIn Clean SlideMaster.vsto"



    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: where am I and what’s here?
        run: |
          Write-Host "PWD =" (Get-Location)
          Get-ChildItem -Recurse -Filter *.slnx | Select-Object FullName
          Get-ChildItem -Recurse -Filter *.csproj | Select-Object FullName


      - name: Build (strong-name happens via project settings)
        run: |
          write-host $Env:SOLUTION_FILE /p:Configuration=$Env:CONFIGURATION /m
          msbuild $Env:SOLUTION_FILE /p:Configuration=$Env:CONFIGURATION /m



      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          write-host Add other actions to build,
          write-host test, and deploy your project.
